### ISSUE TITLE
Documenting possible causes for TypeError: t.tags is undefined

### ISSUE THREAD

**Issue by jmp75** [danielfrg/jupyter-flex#105]
I got a "Something went wrong while building the dashboard" error with `TypeError: t.tags is undefined`  while developing a dashboard. 

Located the cause after a bit of sleuthing. 

For the record if someone else bumps in the same error message.

I am using `jupytext` to synchronise a notebook with a plain text version; that helped me locate a cell with a  "body" tag before any card/page being defined via a markdown cell. That happened after a refactor splitting and moving cells.

```python
# %% tags=["body"]
```

So if you get that error do check the tags in each cells. 

There  may be a way to improve error messages also.

**Comment by danielfrg** [comment]
I just tried this with on a simple notebook with one cell and it works for me on the latest version.

Notebook: https://github.com/danielfrg/jupyter-flex/blob/main/examples/layouts/single-card.ipynb

I am going to close but if you have a sample notebook that is indeed broken pls upload it here so we can fix it.
