### ISSUE TITLE
jupyter-flex command line app not responding to ctrl-c on Windows

### ISSUE THREAD

**Issue by jmp75** [danielfrg/jupyter-flex#106]
Minor issue, but may be troubling for some users. I noticed that on Windows if jupyter-flex is started and running on the default port, but not accessed by a browser, the command line app is not terminating when CTRL-C is sent. 

If triggering an access to localhost:8866 from a browser, however, immediately the server stops.

**Comment by jmp75** [comment]
It may be a Voila issue rather than jpt-flex.

**Comment by danielfrg** [comment]
We removed the cli on 0.9.0 so if this happens its voila now.
