### ISSUE TITLE
Can we not get flex html output with a ipywidget in jupyter-flex?

### ISSUE THREAD

**Issue by arind123** [danielfrg/jupyter-flex#107]
Hi everyone, this is not an issue as per say,  but an enquiry.
I am trying to output a ipywidget inside the dashboard. I can host it using **"jupyter-flex notebook.ipynb"** and the widget shows up. But when I try to download as flex(HTML). It says **"loading widget"** and stays like that. 
Is this an issue or it cannot be done in a html file? Like, we cannot add ipywidgets in the html files that can downloaded and shared?

Package versions:
jupyter                       1.0.0
jupyter-client                7.1.2
jupyter-console               6.4.0
jupyter-core                  4.9.1
jupyter-flex                  0.8.0
jupyter-lsp                   1.5.1
jupyter-server                1.13.5
jupyterlab                    3.2.9
jupyterlab-lsp                3.10.0
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.2
urllib3                       1.26.8
voila                         0.2.16
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.2.3
wheel                         0.37.1
widgetsnbextension            3.5.

**Comment by raissa-amaral** [comment]
Hey, I'm having the same issue. Have you figured out a solution @arind123 ?

Thanks!
![image](https://user-images.githubusercontent.com/97529725/158376324-1020c10c-965b-430a-977e-2d9fff1f35b1.png)

**Comment by danielfrg** [comment]
I dont think this is supported in regular nbconvert exported html files.
If it works with the regular template please re open.
