### ISSUE TITLE
generating static HTML with a specified CDN

### ISSUE THREAD

**Issue by ricky-lim** [danielfrg/jupyter-flex#18]
First of all, I'd like to say thank you for the library and I found it very useful.

I was wondering if you could give me a reference on specifying alternative CDN in the `jupyter nbconvert`, other than https://unpkg.com, in the case that a static file is not found, please.

Thanks in advance.

**Comment by danielfrg** [comment]
All the assets, including third-party JS libraries should be included in the HTML.

I kinda decided to do it that way to make the dashboard self contained and avoid any CDN issues. Are there any resources that are not complaint with that?
