### ISSUE TITLE
Fix qgrid

### ISSUE THREAD

**Issue by danielfrg** [danielfrg/jupyter-flex#20]
I think this is broken in the latest versions of the packages.

**Comment by hickmanw** [comment]
No problems for me with qgrid 1.3.1 and jupyter-flex 0.5.0

**Comment by hickmanw** [comment]
But qgrid doesn't work for me after `build make` from 75e444fccac1d74b82c137e0a4a8cd68ef3791cb

**Comment by hickmanw** [comment]
While I'm here, thanks for sharing jupyter-flex! I'm working on an interactive dashboard, and was happy to find this package.

**Comment by danielfrg** [comment]
Thanks for the feedback, happy to see it's been useful!

And thanks for commenting on the use so I know that I actually have to fix it before the next release :D
