### ISSUE TITLE
Change navbar color

### ISSUE THREAD

**Issue by zbouslikhin** [danielfrg/jupyter-flex#25]
Hi,
I'm really enjoying your work. It really makes it easier to quickly create a dynamic notebook, wonderful package!

I was wondering if it is possible to change the color of the nav bar located on the very top of the dashboard?

![image](https://user-images.githubusercontent.com/47977073/83503955-2b95bc00-a4c4-11ea-9e39-948f9a38d112.png)

Looking forward for your answer!

Cheers,
Zaid

**Comment by danielfrg** [comment]
Hi Zaid,

I think you might be able to customize this by adding a `custom.css` to the same directory you where the notebook `.ipynb` file is located. This file is loaded by default so you should be able to change this.

You could also probably add a notebook cell that outputs the CSS code to the notebook.

In either case you would just overwrite the default CSS of the header.

Let me know if that works for you.

I will keep this open as I have plans to make this easier at one point.

**Comment by zbouslikhin** [comment]
Hi Daniel,

Indeed, by adding a `custom.css` and changing the priority of the  item to `!important`, forces the navbar color to change.

Here is the small piece of code:

![image](https://user-images.githubusercontent.com/47977073/83726867-76d6d880-a644-11ea-8563-3699c54f3852.png)

Thanks,
Zaid

**Comment by danielfrg** [comment]
Thanks for reporting back. I am gonna close this as the current options are probably good enough for every to customize the dashboard.

Thanks for the feedback!
