### ISSUE TITLE
Support flex_logo and flex_favicon

### ISSUE THREAD

**Issue by agoose77** [danielfrg/jupyter-flex#47]
Hi @danielfrg, thanks for all of the hard work here, it's a great package.

I noticed that `flex_logo` doesn't do anything in `0.6.1` and I assume from the source code that `flex_favicon` does not either. Are these planned features, or have they been removed?

Thanks!

**Comment by danielfrg** [comment]
Ah yes, I forgot to migrate those to the new React codebase. Definitely want to support those.

**Comment by agoose77** [comment]
@danielfrg do you plan on performing a new release for these, or would I be better installing via git? :)

**Comment by agoose77** [comment]
That would be quite handy @danielfrg - installing via Git is a little trickier than it should be using poetry without a virtualenv, and I'd like to avoid bundling `jupyter-flex` as a submodule to reduce the number of failure points for my team!

**Comment by danielfrg** [comment]
I just uploaded version 0.6.2: https://pypi.org/project/jupyter-flex/0.6.2/

**Comment by agoose77** [comment]
This is fantastic, thank you! :sparkles:
