### ISSUE TITLE
Read Jupyter's magic cell

### ISSUE THREAD

**Issue by zbouslikhin** [danielfrg/jupyter-flex#48]
Hi,

I'm using Jupyter's magic cells to run, say a JS file. 
I noticed that the magic cell is skipped and therefore not run when the nb is run through Jupyter-flex. Is there a way to work it through or a method to run it that I'm not aware of?
![image](https://user-images.githubusercontent.com/47977073/90152598-45873100-dd88-11ea-9ae6-3ac671aed5c7.png)
Looking forward for your answer!

Cheers,
Zaid

**Comment by zbouslikhin** [comment]
cc @danielfrg

**Comment by danielfrg** [comment]
Not sure why magic cells are not being executed but you can just use the IPython functions instead as the magics are just wrappers for these.

See this example: https://github.com/danielfrg/jupyter-flex/blob/master/examples/demos/data-types.ipynb
