### ISSUE TITLE
Design: support CSS flex/grid layouts?

### ISSUE THREAD

**Issue by agoose77** [danielfrg/jupyter-flex#50]
Hi @danielfrg,

Do you think that it is in the scope of this package to support CSS responsive layouts e.g. flex or grid? I see that it currently uses flex, but there is no support for wrapping as far as I am aware.

This is not a feature request per se, more of a discussion point.

**Comment by agoose77** [comment]
Since opening the issue, I have decided that a two-column fixed layout would suit better for my needs. But, I think it might be a nice feature to have a flex layout, where the user is able to enable wrapping on the section. 

I'm not going to open an issue making a feature request, I'd rather open a PR if I do need this feature, so I'll close this issue for now.

**Comment by danielfrg** [comment]
I am not sure if i am missing something. If all you need is to set the `flex-wrap` property you should be able to do that using any custom CSS.

Supporting grid layouts is not something I am planning but if there are good reasons for it, mostly some flexibility on dashboard design and a good Notebook API (tags) we can use I am open to that.

**Comment by agoose77** [comment]
You can set flex-wrap, but right now the various margins assume a single row/column. However, you are correct -this can all be done with custom CSS so I don't think it's a big issue :)
