### ISSUE TITLE
Issue with section-tabs

### ISSUE THREAD

**Issue by chaydenfowler** [danielfrg/jupyter-flex#56]
Firstly, thank you for the work you've put into this project. I loved Flexdashboard and am happy to see a python instalment.

The issue:
Section Tabs are failing to work for me as done in '[examples/layouts/pages.ipynb](https://github.com/danielfrg/jupyter-flex/blob/master/examples/layouts/pages.ipynb)' and '[examples/layouts/section-tabs-rows.ipynb](https://github.com/danielfrg/jupyter-flex/blob/master/examples/layouts/section-tabs-rows.ipynb)'.
When clicking on a section tab (tabs tag on ## header) the page goes blank with no selectable options in the body - Page selection still remains as an option.

To take pages.ipynb as an example:
The starting URL is `[main_url]#/`

1. Clicking the 'Page 2' tab brings me to `[main_url]#/page-2` yielding expected behaviour.
2. Clicking on 'Page 2' then onto 'Page 2 - Row 1 - Tab 2' tab brings me to `[main_url]#/page-2-row-1-tab-2` with blank content yielding unexpected behaviour. This link might rather be something like `[main_url]#/page-2/page-2-row-1-tab-2`?
3. Clicking on 'Page 1' then onto 'Col 2 - Tab 2' brings me to `[main_url]#/col-2-tab-2` with blank content yielding unexpected behaviour.

This behaviour only occurs on Flex Dashboard HTML (behaves as expected with voila).

Tangentially I get errors in the Flex Dashboard HTML regardless of whether the page is producing expected behaviour or not:
![image](https://user-images.githubusercontent.com/15724863/94767344-97534b80-0408-11eb-9340-fb21923caef4.png)
(Voila produces no such errors)

First thoughts are I'm missing some external dependency somewhere?

Pip list with minimum packages to reproduce (i.e pip install jupyter jupter-flex traitlets==4.3.2):
```
Package             Version
------------------- -------
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.2.0
backcall            0.2.0
bleach              3.2.1
cffi                1.14.3
colorama            0.4.3
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
importlib-metadata  2.0.0
ipykernel           5.3.4
ipython             7.18.1
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
Jinja2              2.11.2
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.7
jupyter-console     6.2.0
jupyter-core        4.6.3
jupyter-flex        0.6.2
jupyter-server      0.1.1
jupyterlab-pygments 0.1.2
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.0
nbconvert           5.6.1
nbformat            5.0.7
nest-asyncio        1.4.1
notebook            6.1.4
packaging           20.4
pandocfilters       1.4.2
parso               0.7.1
pickleshare         0.7.5
pip                 19.2.3
prometheus-client   0.8.0
prompt-toolkit      3.0.7
pycparser           2.20
Pygments            2.7.1
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pywin32             228
pywinpty            0.5.7
pyzmq               19.0.2
qtconsole           4.7.7
QtPy                1.9.0
Send2Trash          1.5.0
setuptools          41.2.0
six                 1.15.0
terminado           0.9.1
testpath            0.4.4
tornado             6.0.4
traitlets           4.3.2
voila               0.1.23
wcwidth             0.2.5
webencodings        0.5.1
widgetsnbextension  3.5.1
zipp                3.2.0
```

**Comment by chaydenfowler** [comment]
I've encountered (what I believe to be) a completely separate issue also relating to section-tabs that I will append to this issue thread. When using Plotly charts, charts on tabs other than the first are not auto-scaled unless you manually resize the window on entry to the tab - this resets when you exit and re-enter the page.

Not a game-breaking issue, but an annoying one for sure. I haven't tested any other setups. Charts are identical in the properties set in python code.

This behaviour is with Voila (cannot get HTML only to work as described in top comment). When viewing the resultant HTML the contents of the div with the class="plotly-container plotly" is distinctly different between the first tab and all subsequent tabs. The main inconsistences are:
- the presence of a second ```class="sc-AxhUy fxWvvr"``` div
- The ```class="svg-container"``` div width and heights being from 100% to px.

The heights and widths update when resizing the window, however the plot height and width plots initialise at ```width: 700px; height: 450px;``` for tabs that aren't the first one.

First tab plotly-container div - resized window:
![image](https://user-images.githubusercontent.com/15724863/94887790-b23ec200-04d3-11eb-817e-731bf8c3df62.png)


Second tab plotly-container div - resized window:
![image](https://user-images.githubusercontent.com/15724863/94887567-29c02180-04d3-11eb-9a1b-bcf678347fef.png)

**Comment by chaydenfowler** [comment]
Update on issues:

1. The main issue of section tabs failing in HTML-only seems to be fixed in dev build 0.6.3 - thank you for this.
Installing the package was a short journey in itself - for completeness and for others, rough instructions to do so are:
- git clone the repo
- in the top directory of the local repo: `make npm-install`
- `make build`
- go to the folder `\python\dist\`
- `pip install [the new jupyter-flex.tar.gz file]`
2. The tangential errors/warnings in the Flexdashboard HTML 
For completeness - The yellow warnings are just for expanding minified javascript for development and can be evaded by moving the files `venv\share\jupyter\voila\templates\flex\static\dist\FlexRenderer.js.map` and `FlexRenderer.css.map` into the local directory when opening the HTML - not particularly useful, as I couldn't even figure out how to meaningfully edit the unminified JS source when trying to fix number 1.
The red errors however are still somewhat a mystery to me - Attempts to replace the integrity with a valid hash seemed to only break things further (with css disappearing etc) despite fewer errors appearing - very unsure what's going on here.
3. The plotly section resizing is still inconsistent in the same way as of dev build 0.6.3, 

Number 3 is the only thing I see preventing this issue being closed.

**Comment by danielfrg** [comment]
Thanks for the updates!

Yes, the packages has deps for development that are a little bit harder but we have a DEVELOP.md that should help a bit.

I will be taking a look at the plotly issues soon.

**Comment by chaydenfowler** [comment]
Thank you for the info; if I actually used my eyes I might have found DEVELOP.md

New problem, if you haven't caught it already:
4. Classes no longer work on body as seen in '[examples/customize/classes-colors.ipynb](https://github.com/danielfrg/jupyter-flex/blob/master/examples/customize/classes-colors.ipynb)'. Can't get this to work on 0.6.2 or 0.6.3

![image](https://user-images.githubusercontent.com/15724863/95404168-c588dc00-0970-11eb-8bf6-20626011a0cb.png)
