### ISSUE TITLE
Print Specific Cards Output to PDF

### ISSUE THREAD

**Issue by jakuboo** [danielfrg/jupyter-flex#77]
First of all: This thing is great! Good job!

I have a dashboard built with multiple pages, pages have cards with tabs. I have charts located on the tabs. I want to incorporate a "button" that will produce a report PDF with some of the tab charts. 

Do you have any idea how this can be done? 
1. I was thinking about adding another page where I would duplicate all the charts I want to put onto the report. Is it possible to allow for the vertical scroll on just a single page? Parameter `flex_vertical_layout `
2. I was thinking about other modules like nbconvert which can remove cells based on `tag`. But will additional tags mess the jupter-flex dashboard?

**Comment by danielfrg** [comment]
1. I have not tested a different pages with different layouts but I think its supported by having a tag like this `vertical_layout=scroll`, if now we should support this.

2. In general additional tags will not mess the dashboard layout unless there is a conflict with the one we use internally, but other ones will not have an effect and you have just have them as usual

**Comment by danielfrg** [comment]
Update about 1, i can confirm it doesnt work in the latest version.
