### ISSUE TITLE
jupyter-flex uncaught exception

### ISSUE THREAD

**Issue by tpaixao** [danielfrg/jupyter-flex#78]
Jupyter-flex works great on windows, but when I try to deploy it in a linux server (using voila) I get the following error on the console and the application stays on the "loading widget" spinner forever.
```
Uncaught (in promise) TypeError: Cannot read property 'kernelChanged' of undefined
    at new so (voila.js:455)
    at new Ys (voila.js:469)
    at index.js:90
```

looking at the network tab of DevTools indicates that everything is loading fine.  The dashboard loads fine using the lab template. Perhaps some race condition when loading stuff?

Could really use some help on this!

here's my environment:

anyio==2.2.0
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
bleach==3.3.0
cffi==1.14.5
cycler==0.10.0
decorator==5.0.7
defusedxml==0.7.1
entrypoints==0.3
idna==3.1
ipykernel==5.5.3
ipysheet==0.4.4
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-flex==0.6.4
jupyter-server==1.6.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
MarkupSafe==1.1.1
matplotlib==3.4.1
mistune==0.8.4
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
numpy==1.20.2
packaging==20.9
pandas==1.2.4
pandocfilters==1.4.3
parso==0.8.2
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
prometheus-client==0.10.1
prompt-toolkit==3.0.18
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.8.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pyzmq==22.0.3
scipy==1.6.2
seaborn==0.11.1
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
statsmodels==0.12.2
terminado==0.9.4
testpath==0.4.4
tornado==6.1
traitlets==5.0.5
voila==0.2.9
voila-gridstack==0.2.0
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1

**Comment by tpaixao** [comment]
an extra comment: the original error seems to come from `jupyter-flex-embed.js`. The entry in the console briefly flags this file, before changing to index.js .

**Comment by danielfrg** [comment]
It's good to know it works on windows as we dont do that much testing there :D

Is it possible for you to generate a minimal notebook (as few cells and deps that makes the error happen) that I can use to reproduce the issue?

**Comment by tpaixao** [comment]
Thanks for taking a look (and obviously for developing this - it's great!)! I have been using the one on the documentation. Attached, together with a requirements.txt that you can use to reproduce the environment. 

[test.zip](https://github.com/danielfrg/jupyter-flex/files/6320135/test.zip)

**Comment by tpaixao** [comment]
so.... today it suddenly started working. not sure what happened, and sorry for the trouble. I will close it now.

**Comment by eraldop** [comment]
@tpaixao did you notice what changed in your configuration that fixed the issue? I'm on macos but I'm experiencing your same issue.

**Comment by tpaixao** [comment]
Honestly, no idea. I think I rebooted the server but have no idea why that would resolve the issue. At the time, I suspected that it had something to do with how I was serving static files (I am using nginx). There might be some sort of race condition, with some javascript getting loaded before others, but this is just a not very informed guess...

**Comment by tsdev** [comment]
I also had some issues for a few days on our hosted Jupyter server running Linux. I would try out the patch merged 2 days ago, but I don't see it showing up on PyPi.
