### ISSUE TITLE
widgets not rendering when using Voilà and flex template

### ISSUE THREAD

**Issue by eraldop** [danielfrg/jupyter-flex#79]
Using jupyter-flex with Voilà (--template flex) doesn't render any widget. I'm using "iris-clustering.ipynb". Removing the request for the flex template solves the problem but, of course, makes it useless to adopt jupyter-flex. 

Running notebooks without proper widgets ("nba-scoring.ipynb") goes smoothly. 

I tried starting from a clean environment (created with conda - python 3.8) without success. The same result starting from a development installation of jupyter-flex using its configuration (followed step-by-step in one case and using "make env" alone in another attempt). 

Running voilà in debug mode doesn't show any particular error. 

Checking html output shows this error: 

<img width="1314" alt="Schermata 2021-04-26 alle 16 45 19" src="https://user-images.githubusercontent.com/588022/116102661-30042e00-a6af-11eb-88bc-7dfdf2aeeeb0.png">

Exporting the notebook in "flex" format doesn't solve the problem.

I'm running mac-os Big Sur (11.2.3)

Any help is appreciated. Thanks. 

Test output: 

<img width="1502" alt="Schermata 2021-04-26 alle 17 12 32" src="https://user-images.githubusercontent.com/588022/116106729-abb3aa00-a6b2-11eb-9152-cf7f4b74c50c.png">

**Comment by eraldop** [comment]
It seems to be exactly the same behaviour described in the closed issue #78.

**Comment by danielfrg** [comment]
This was indeed a bug with the latest voila, for now I would advice in downgrading it but still stay on the `0.2.x` versions. I will try to do a release soon.
