### ISSUE TITLE
Hide/show Sidebar?

### ISSUE THREAD

**Issue by sachin-smart** [danielfrg/jupyter-flex#86]
First of all, thank you for the fantastic package!

I have created a dashboard that uses a sidebar for various inputs. However, it is useful screen real estate that it takes up, so I was wondering if there would be any way to have the sidebar appear/disappear either with a button or based on mouse location?

I think this would be a useful future for many. I'm, of course, open to suggestions on alternatives.

Thanks!

**Comment by danielfrg** [comment]
This has been added on https://github.com/danielfrg/jupyter-flex/commit/d2c825d3966190cd8181184eadbe106326dac9e0

I will test the next couple of days and try to make a release soon!

**Comment by sachin-smart** [comment]
That's great news. Thanks!
