### ISSUE TITLE
Unable to nbconvert or save jupyter notebook as flex dashboard html

### ISSUE THREAD

**Issue by joshuamosesb** [danielfrg/jupyter-flex#88]
I'm running `jupyter notebook` with python=3.9,pandas=1.2.5 (in a separate conda environment)
I installed `nbconvert`, `jupyter-flex` using `pip install` as given in [jupyter-flex-getting-started](https://jupyter-flex.danielfrg.com/getting-started/) within the conda environment
I could add page, section & card elements with the cell tags; but not getting the save-as option as referred in: [save-as-flex-dashboard](https://jupyter-flex.danielfrg.com/assets/img/getting-started/download-as.png)

Also tried to run `jupyter nbconvert --to flex dashboard_prototype_with_charts_data.ipynb --execute` but `--to flex` is not being recognized as valid format
not sure if I'm missing any other base settings, pls help.

**Comment by danielfrg** [comment]
There is nothing else you need to run this, this is most likely due to not being in the correct env, be sure you have it activated.

You could also check that the files are in the environment share directory, for example this dir should exist:

```
<your-conda-env-path>/share/jupyter/nbconvert/templates/flex
```

Also maybe try updating jupyter to the latest version, they changed the template location at one point.

**Comment by joshuamosesb** [comment]
thank you Daniel.
flex sub-dir was not found under: ```D:\ProgramData\Anaconda3\envs\pd125\share\jupyter\nbconvert\templates```
Pls find below the environment info for:
- jupyter-flex:
  ```Name: jupyter-flex
    Version: 0.5.0
    Summary: Voila Flex Dashboards
    Home-page: https://github.com/danielfrg/jupyter-flex
    Author: Daniel Rodriguez
    Author-email: df.rodriguez143@gmail.com
    License: Apache 2.0
    Location: d:\programdata\anaconda3\envs\pd125\lib\site-packages
    Requires: nbconvert, voila
    Required-by:```
 - nbconvert:
    ```Name: nbconvert
    Version: 6.1.0
    Summary: Converting Jupyter Notebooks
    Home-page: https://jupyter.org
    Author: Jupyter Development Team
    Author-email: jupyter@googlegroups.com
    License: BSD
    Location: d:\programdata\anaconda3\envs\pd125\lib\site-packages
    Requires: pandocfilters, jinja2, nbformat, jupyterlab-pygments, pygments, mistune, entrypoints, nbclient, defusedxml, traitlets, testpath, jupyter-core, bleach
    Required-by: voila, notebook, jupyter, jupyter-server, jupyter-flex```
 - conda environment:
   ``` active environment : pd125
      active env location : D:\ProgramData\Anaconda3\envs\pd125
      shell level : 2
      user config file : C:\Users\Joshua\.condarc
      populated config files : C:\Users\Joshua\.condarc
      conda version : 4.8.4
      conda-build version : 3.18.11
      python version : 3.7.6.final.0
      virtual packages :
      base environment : D:\ProgramData\Anaconda3  (writable)
      package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\Joshua\.conda\pkgs
                          C:\Users\Joshua\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\Joshua\.conda\envs
                          C:\Users\Joshua\AppData\Local\conda\conda\envs
       platform : win-64
       user-agent : conda/4.8.4 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
       administrator : True
       netrc file : None
       offline mode : False
```

**Comment by danielfrg** [comment]
You have an old version of jupyter-flex, try upgrading to `0.6.5` i think we updated the paths to jupyter 6.0.0 on our 0.6.X versions

**Comment by joshuamosesb** [comment]
Thank you Daniel; I was able to upgrade to 0.6.5; `D:\ProgramData\Anaconda3\envs\pd125\share\jupyter\nbconvert\templates\flex` is present as expected.
-----
Just posting below update, if other face similar issue:
Since `git` was not in my system path `pip install -U jupyter-flex` was failing to install the latest version; adding git to system path, helped to update jupyter-flex
